// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import "forge-std/Script.sol";
import "../src/Verifier.sol"; // Generated by bb contract

contract DeployVerifier is Script {
    function run() external {
        uint256 deployerPrivateKey = vm.envUint("PRIVATE_KEY");

        vm.startBroadcast(deployerPrivateKey);

        UltraVerifier verifier = new UltraVerifier();
        console.log("Verifier deployed to:", address(verifier));

        vm.stopBroadcast();
    }
}
