// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import "forge-std/Test.sol";
import "../src/Verifier.sol"; // Generated by bb contract

contract NoirVerifierForkTest is Test {
    UltraVerifier public verifier;

    function setUp() public {
        // Fork Sepolia if RPC URL is provided
        string memory rpcUrl = vm.envOr("SEPOLIA_RPC_URL", string(""));
        if (bytes(rpcUrl).length > 0) {
            vm.createSelectFork(rpcUrl);
        }

        // Deploy verifier
        verifier = new UltraVerifier();
    }

    function testDeploymentGasCost() public {
        uint256 gasBefore = gasleft();
        UltraVerifier newVerifier = new UltraVerifier();
        uint256 gasUsed = gasBefore - gasleft();

        console.log("Deployment gas:", gasUsed);
        assertLt(gasUsed, 2_000_000, "Deployment should cost < 2M gas");
    }

    function testVerificationGasCost() public {
        bytes memory proof = vm.readFileBinary("../../proof_image.groth16.proof");
        bytes memory publicInputs = vm.readFileBinary("../../proof_image.public_inputs");

        uint256 gasBefore = gasleft();
        verifier.verify(proof, publicInputs);
        uint256 gasUsed = gasBefore - gasleft();

        console.log("Verification gas:", gasUsed);
        assertLt(gasUsed, 500_000, "Verification should cost < 500K gas");
    }

    function testForkVerification() public {
        bytes memory proof = vm.readFileBinary("../../proof_image.groth16.proof");
        bytes memory publicInputs = vm.readFileBinary("../../proof_image.public_inputs");

        bool isValid = verifier.verify(proof, publicInputs);
        assertTrue(isValid, "Valid proof should verify on fork");
    }
}
