// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import "forge-std/Test.sol";
import "../src/Verifier.sol"; // Generated by bb contract

contract NoirVerifierTest is Test {
    UltraVerifier public verifier;

    function setUp() public {
        verifier = new UltraVerifier();
    }

    function testVerifyValidProof() public {
        // Load pre-generated proof and inputs
        bytes memory proof = vm.readFileBinary("../../proof_image.groth16.proof");
        bytes memory publicInputs = vm.readFileBinary("../../proof_image.public_inputs");

        // Verify
        bool isValid = verifier.verify(proof, publicInputs);
        assertTrue(isValid, "Valid proof should verify");
    }

    function testRejectInvalidProof() public {
        bytes memory validProof = vm.readFileBinary("../../proof_image.groth16.proof");
        bytes memory publicInputs = vm.readFileBinary("../../proof_image.public_inputs");

        // Corrupt proof by flipping bits in first byte
        bytes memory invalidProof = new bytes(validProof.length);
        for (uint i = 0; i < validProof.length; i++) {
            invalidProof[i] = validProof[i];
        }
        invalidProof[0] = bytes1(uint8(invalidProof[0]) ^ 0xFF);

        // Should reject
        vm.expectRevert();
        verifier.verify(invalidProof, publicInputs);
    }

    function testRejectInvalidPublicInputs() public {
        bytes memory proof = vm.readFileBinary("../../proof_image.groth16.proof");
        bytes memory validInputs = vm.readFileBinary("../../proof_image.public_inputs");

        // Corrupt public inputs
        bytes memory invalidInputs = new bytes(validInputs.length);
        for (uint i = 0; i < validInputs.length; i++) {
            invalidInputs[i] = validInputs[i];
        }
        invalidInputs[0] = bytes1(uint8(invalidInputs[0]) ^ 0xFF);

        // Should reject
        vm.expectRevert();
        verifier.verify(proof, invalidInputs);
    }
}
