// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import {Test} from "forge-std/Test.sol";
import {console2} from "forge-std/console2.sol";
import {RorschachVerifier} from "../src/RorschachVerifier.sol";
import {IRiscZeroVerifier} from "../src/IRiscZeroVerifier.sol";

/// @notice Mock verifier for testing
contract MockRiscZeroVerifier is IRiscZeroVerifier {
    bool public shouldRevert;

    function setShouldRevert(bool _shouldRevert) external {
        shouldRevert = _shouldRevert;
    }

    function verify(
        bytes calldata,
        bytes32,
        bytes32
    ) external view override {
        if (shouldRevert) revert("Mock verification failed");
    }
}

contract RorschachVerifierTest is Test {
    RorschachVerifier public verifier;
    MockRiscZeroVerifier public mockVerifier;

    address constant TEST_ADDRESS = 0x19E7E376E7C213B7E7e7e46cc70A5dD086DAff2A;
    uint64 constant TEST_WALKS = 5;
    uint64 constant TEST_STEPS = 211;

    function setUp() public {
        mockVerifier = new MockRiscZeroVerifier();
        verifier = new RorschachVerifier(IRiscZeroVerifier(address(mockVerifier)));
    }

    function testVerifyImage() public {
        // Create test journal data (ABI-encoded)
        bytes memory binaryImage = new bytes(256);
        for (uint i = 0; i < 256; i++) {
            binaryImage[i] = bytes1(uint8(i));
        }

        bytes memory journal = abi.encode(
            TEST_ADDRESS,
            TEST_WALKS,
            TEST_STEPS,
            binaryImage
        );

        bytes memory seal = hex"1234"; // Mock seal

        // Verify image
        bool success = verifier.verifyImage(seal, journal);
        assertTrue(success);

        // Check storage
        bytes32 imageHash = keccak256(binaryImage);
        assertTrue(verifier.isVerified(imageHash));

        // Check address mapping
        bytes32[] memory images = verifier.getAddressImages(TEST_ADDRESS);
        assertEq(images.length, 1);
        assertEq(images[0], imageHash);
    }

    function testVerifyImageInvalidSize() public {
        bytes memory binaryImage = new bytes(100); // Wrong size
        bytes memory journal = abi.encode(TEST_ADDRESS, TEST_WALKS, TEST_STEPS, binaryImage);
        bytes memory seal = hex"1234";

        vm.expectRevert(RorschachVerifier.InvalidImageSize.selector);
        verifier.verifyImage(seal, journal);
    }

    function testVerifyImageAlreadyVerified() public {
        bytes memory binaryImage = new bytes(256);
        bytes memory journal = abi.encode(TEST_ADDRESS, TEST_WALKS, TEST_STEPS, binaryImage);
        bytes memory seal = hex"1234";

        verifier.verifyImage(seal, journal);

        vm.expectRevert(RorschachVerifier.AlreadyVerified.selector);
        verifier.verifyImage(seal, journal);
    }

    function testVerifyOwnership() public {
        bytes memory binaryImage = new bytes(256);
        bytes memory journal = abi.encode(TEST_ADDRESS, TEST_WALKS, TEST_STEPS, binaryImage);
        bytes memory seal = hex"1234";

        bool isOwner = verifier.verifyOwnership(seal, journal, TEST_ADDRESS);
        assertTrue(isOwner);

        bool notOwner = verifier.verifyOwnership(seal, journal, address(0x2222));
        assertFalse(notOwner);
    }

    function testVerifyImageRevertsOnBadProof() public {
        mockVerifier.setShouldRevert(true);

        bytes memory binaryImage = new bytes(256);
        bytes memory journal = abi.encode(TEST_ADDRESS, TEST_WALKS, TEST_STEPS, binaryImage);
        bytes memory seal = hex"1234";

        vm.expectRevert("Mock verification failed");
        verifier.verifyImage(seal, journal);
    }

    function testVerifyRealProof() public {
        // Read the real proof files generated by our Rust program
        string memory root = vm.projectRoot();

        bytes memory seal = vm.readFileBinary(
            string.concat(root, "/../../test_groth16.seal")
        );

        bytes memory journal = vm.readFileBinary(
            string.concat(root, "/../../test_groth16.journal")
        );

        console2.log("Seal size:", seal.length);
        console2.log("Journal size:", journal.length);

        // Decode to check values
        (address ethAddress, uint64 walks, uint64 steps, bytes memory binaryImage) =
            abi.decode(journal, (address, uint64, uint64, bytes));

        console2.log("Address:", ethAddress);
        console2.log("Walks:", walks);
        console2.log("Steps:", steps);
        console2.log("Binary image size:", binaryImage.length);

        // Note: This will pass with mock verifier
        // For real verification, deploy actual risc0 verifier
        bool success = verifier.verifyImage(seal, journal);
        assertTrue(success);

        console2.log("Real proof verified successfully with mock!");
    }
}
